// @generated by checkers-spec-gen. Do not edit.
//
// The law registry for wasm32, where `linkme` cannot collect anything (no
// linker-defined section-boundary symbols exist to take the address of).
// Native builds ignore this file entirely and use the distributed slice,
// which is the authority this file is derived from.
//
// Regenerate:      cargo run -p checkers-spec-gen -- --emit-registry
// Check freshness: cargo run -p checkers-spec-gen -- --check-registry

// law-ids: CC-APPLY-NET,CC-DIR-INVOLUTION,CC-GEO-BASE-CAMP,CC-GEO-CAMP-OF,CC-GEO-CARDINALITY,CC-GEO-CONTACT,CC-GEO-DISJOINT,CC-GEO-INWARD-BAD,CC-GEO-INWARD-CONTACT,CC-GEO-NONVACUOUS,CC-GEO-OPPOSITE,CC-GEO-ROT-EXACT,CC-GEO-ROT-NEG,CC-GEO-ROT-ORDER,CC-GEO-ROT-STEP,CC-GEO-SYMMETRY,CC-INV-PRESERVED,CC-JUMP-ANY-OWNER,CC-JUMP-CLOSURE,CC-JUMP-DISPLACEMENT,CC-JUMP-LEGAL,CC-JUMP-NO-CAPTURE,CC-JUMP-OMEGA,CC-JUMP-REVISIT,CC-MOVE-DEDUP,CC-MOVE-IDENTITY,CC-MOVE-ONBOARD,CC-POS-INITIAL,CC-POS-OCCUPANCY,CC-POS-PIECES,CC-POS-TARGET,CC-STEP-DISPLACE,CC-STEP-LEGAL,CC-TURN-BLOCKED,CC-TURN-CYCLE,CC-TURN-HOP-CLOSURE,CC-TURN-HOP-ONE,CC-TURN-NO-NULL-MOVE,CC-TURN-PASS,CC-TURN-STAGED-LEGAL,CC-VAR-CAMP-FREE,CC-WIN-CONDITION

pub static LAWS: [crate::law::LawInfo; 42] = [
    crate::law_info!(crate::laws::geometry::BaseCampHoles),
    crate::law_info!(crate::laws::geometry::BoardCardinality),
    crate::law_info!(crate::laws::geometry::BoardIsCentrallySymmetric),
    crate::law_info!(crate::laws::geometry::CampContactCount),
    crate::law_info!(crate::laws::geometry::CampOfIsConsistent),
    crate::law_info!(crate::laws::geometry::DirectionsCloseUnderNegation),
    crate::law_info!(crate::laws::geometry::InwardCampContactCount),
    crate::law_info!(crate::laws::geometry::InwardCampIsDegenerate),
    crate::law_info!(crate::laws::geometry::JumpDisplacement),
    crate::law_info!(crate::laws::geometry::OppositeCampIsReflection),
    crate::law_info!(crate::laws::geometry::RegionsAreDisjoint),
    crate::law_info!(crate::laws::geometry::RegionsAreNonVacuous),
    crate::law_info!(crate::laws::geometry::RotationCubedIsNegation),
    crate::law_info!(crate::laws::geometry::RotationOrderIsExact),
    crate::law_info!(crate::laws::geometry::RotationOrderSix),
    crate::law_info!(crate::laws::geometry::RotationPermutesDirections),
    crate::law_info!(crate::laws::rules::BlockedPlayerIsReachable),
    crate::law_info!(crate::laws::rules::CampsAreUnrestricted),
    crate::law_info!(crate::laws::rules::InitialPosition),
    crate::law_info!(crate::laws::rules::JumpClosureIsExact),
    crate::law_info!(crate::laws::rules::JumpDoesNotCapture),
    crate::law_info!(crate::laws::rules::JumpIgnoresOwnership),
    crate::law_info!(crate::laws::rules::JumpLegality),
    crate::law_info!(crate::laws::rules::JumpRoutesCanRevisit),
    crate::law_info!(crate::laws::rules::MoveGenerationIsDeduplicated),
    crate::law_info!(crate::laws::rules::MoveIdentityIgnoresRoute),
    crate::law_info!(crate::laws::rules::MovesStayOnBoard),
    crate::law_info!(crate::laws::rules::OccupancyAccounting),
    crate::law_info!(crate::laws::rules::OccupancyIsPositionDetermined),
    crate::law_info!(crate::laws::rules::PassingAndDraw),
    crate::law_info!(crate::laws::rules::PieceConservation),
    crate::law_info!(crate::laws::rules::PlayPreservesInvariants),
    crate::law_info!(crate::laws::rules::RouteEqualsNetEffect),
    crate::law_info!(crate::laws::rules::SingleHopIsOneJump),
    crate::law_info!(crate::laws::rules::SingleHopsReachTheClosure),
    crate::law_info!(crate::laws::rules::StagedTurnCannotBeANullMove),
    crate::law_info!(crate::laws::rules::StagedTurnYieldsLegalMove),
    crate::law_info!(crate::laws::rules::StepDisplacement),
    crate::law_info!(crate::laws::rules::StepLegality),
    crate::law_info!(crate::laws::rules::TargetCampIsOpposite),
    crate::law_info!(crate::laws::rules::TurnOrderCycles),
    crate::law_info!(crate::laws::rules::WinCondition),
];
